package com.example.state_machine.model;

public enum ProcessState {
    STARTED,
    FILL_PERSONAL_DETAILS,
    ANSWER_ACCOUNT_QUESTIONS,
    KYC_IN_PROGRESS,
    WAITING_FOR_BIOMETRY,
    BIOMETRY_VERIFIED,
    ACCOUNT_CREATED,
    WAITING_FOR_ALL_OWNERS,
    WAITING_FOR_PARENT_CONSENT,
    ACCOUNT_CREATED_LIMITED,
    MINOR_ACCOUNT_IDENTIFIED,
    WAITING_FOR_CONVERSION_CONFIRMATION,
    ACCOUNT_CONVERTED_TO_REGULAR
}
