package com.example.state_machine.model;

public enum ProcessEvent {
    // === Common events ===
    START_FLOW,
    BACK,
    
    // === Minor Account Opening Flow Events ===
    CONTINUE_FLOW,
    BLOCK_FLOW,
    SUBMIT_OCCUPATION,
    SUBMIT_INCOME,
    SUBMIT_EXPENSES,
    GENERATE_DOCUMENT_SCAN,
    PROCESS_SPEECH_TO_TEXT,
    PERFORM_DOCUMENT_MATCH,
    UPLOAD_FACE_RECOGNITION,
    VALIDATE_CUSTOMER_INFO,
    SUBMIT_SIGNATURE,
    SUBMIT_ACCOUNT_ACTIVITIES,
    SUBMIT_STUDENT_PACKAGES,
    SUBMIT_VIDEO,
    SUBMIT_ADDRESS,
    SUBMIT_BRANCH_CHOICE,
    SUBMIT_INFORMATION_ACTIVITIES,
    SUBMIT_ADDITIONAL_QUESTIONS,
    SUBSCRIBE_TO_SERVICE,
    DECLINE_SERVICE,
    SUBMIT_FORMS,
    ACKNOWLEDGE_WARNINGS,
    COMPLETE_WELCOME
}
